### ISSUE TITLE
Error "h() is undefined" when calling layout.

### ISSUE THREAD

**Issue by nagyj2** [hpcc-systems/hpcc-js-wasm#100]
I am trying render a graphviz diagram given by the user but am getting the error `h() is undefined` when I call the `layout` function. I am using writing in Typescript and am unsure what is going wrong. It is my understanding that I need to call layout with the code to render, the output type and the layout method and then I can retrieve the output svg with a callback.

Here is a snippet of code from my project which contains what I currently have.

```typescript
import wasm from '@hpcc-js/wasm';
...
const obj = $('#selector'); // Get specific element from webpage which holds valid graphviz code
const graphText = obj.innerText; // Valid Graphviz from the user

wasm.graphviz.layout(graphText, "svg", "dot").then((svgCode: string) => { 
  obj.innerHTML = svgCode;
});
```

Edit: This is using Firefox 98.0.2 on macOS 11.4.

**Comment by GordonSmith** [comment]
Try using:
```ts
import { graphviz } from '@hpcc-js/wasm';
```

**Comment by GordonSmith** [comment]
Ok - this is progress! 

FWIW the `import wasm from '@hpcc-js/wasm';` can be problematic as TypeScript will interpret it in different ways depending on what settings you have on the CLI or in the tsconfig.json...

So this new error is basically saying "I tried to load the wasm file, but couldn't locate it in the default location".  To fix it you have two choices:
1.  Press F12 in your web browser and select the "Network" tab.  Reload your webpage (Juyptr Notebook) and it should log when (and where) it tries to load the wasm file from.  Once you know the location, simply copy the graphviz.wasm file the dist folder in @hpcc-js/wasm (in node_modules) to that location.
2.   Use the "wasmFolder" API call (https://github.com/hpcc-systems/hpcc-js-wasm#wasmFolder) to specify the location of the wasm file (excluding the filename).

Note:  If using 1, remember to recopy every time you upgrade to a new version as the wasm and JS have to be in sync...

**Comment by nagyj2** [comment]
Ok, so I went with the `wasmFolder` solution as I'm not always going to know where it is on the extension user's machine. For the meantime, I have modified my installation code so that the wasm library is simply copied into a subfolder and use `wasmFolder()` to tell `@hpcc-js/wasm` where it is. With this solution, the Network tab shows that the wasm library is found.

However, I now have `Uncaught (in promise) RuntimeError: Aborted(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -s ASSERTIONS=1 for more info` errors being thrown. My test graph is `A->B`. I'm not sure if this is a problem with my wasm/ extension setup or the graph.

**Comment by GordonSmith** [comment]
1.  The way I treat wasm files is the same as any resource (like a png or a font) and also end up copying them to a "known" location so they can be found.
2. Your error is the one we typically see when the JS and wasm file are from two different versions, can you double / triple check that the `import { graphviz } from '@hpcc-js/wasm';` and the wasm file are both accessing the same version?

**Comment by nagyj2** [comment]
What do you mean that JS and wasm can be from two different versions? How can I check the version of wasm used by the import? As far as I was aware, there was only one version of webassembly. Looking at the binary wasm file in a hexdump gives me the expected "00 61 73 6d 01 00 00 00" preamble

I tried using the graphvizVersion function exposed by `hpcc-js/wasm` but I get errors out of this. I think its because that function cannot get a connection to webassembly either. The error is:

    wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type 'text/html; charset=utf-8' expected 'application/wasm'
    falling back to ArrayBuffer instantiation [943.41f767ff492c2e8fd259.js:1:91736](http://localhost:8888/lab/extension/unicode-snippets/static/943.41f767ff492c2e8fd259.js?v=41f767ff492c2e8fd259)
     failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 4: failed to match magic number [943.41f767ff492c2e8fd259.js:1:91286](http://localhost:8888/lab/extensions/unicode-snippets/static/943.41f767ff492c2e8fd259.js?v=41f767ff492c2e8fd259)
    Aborted(CompileError: wasm validation error: at offset 4: failed to match magic number)

**Comment by GordonSmith** [comment]
If your project was using the JS from @hpcc-js/wasm@1.14.1 and the wasm file from @hpcc-js/wasm@1.13.0 then you would see that error.

Also you will see that error, if the web server returns 404 html error instead of the file.

This is what a healthy load looks like:
![image](https://user-images.githubusercontent.com/966863/161899398-94f6bba1-f5e3-49bc-b447-dc91c71de6c0.png)

**Comment by GordonSmith** [comment]
Closing as invalid for now, please reopen if you feel this is in error.
