### ISSUE TITLE
Module not found: Can't resolve 'fs/promises' 

### ISSUE THREAD

**Issue by mrdrogdrog** [hpcc-systems/hpcc-js-wasm#115]
Hello,

I try to use the latest version (1.15.4) in a next.js project but if I try to create a build then I get this error:

```
./node_modules/@hpcc-js/wasm/dist/index.js
Module not found: Can't resolve 'fs/promises' in 'node_modules/@hpcc-js/wasm/dist'
```

Using the workaround from https://github.com/vercel/next.js/issues/7755 doesn't work because, even if it compiles then, the browser tries to use the fs package which doesn't exist obviously.

I don't know which version introduced this bug because I upgraded from 1.12.8

**Comment by GordonSmith** [comment]
@mrdrogdrog I was unable to test against next.js, but I did add tests for "esbuild" which is probably as strict when it comes to bundling "require" statements.

Can you test with latest and report back?

**Comment by mrdrogdrog** [comment]
@GordonSmith 

Nope. Sorry :/

![image](https://user-images.githubusercontent.com/6124140/188947205-c288bb73-277b-409b-b7b6-579e33eae7fa.png)

**Comment by mrdrogdrog** [comment]
Seems like just checking the existence of `process` isn't enough.
https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js

**Comment by GordonSmith** [comment]
Hmm the env checking is coming from emscripten...

Quick sanity check - you are building for a browser and not for Node or Deno?

**Comment by GordonSmith** [comment]
Ok I have just tagged a new build (should be in the NPM repo shortly), can you retest and report back?

**Comment by GordonSmith** [comment]
v1.15.6 is released.

**Comment by mrdrogdrog** [comment]
I just nextjs which uses webpack and esbuild to create the browser bundle. 

I'll test the version as soon as I have time.
