### ISSUE TITLE
Error: __require__ call inside web environment???

### ISSUE THREAD

**Issue by mrdrogdrog** [hpcc-systems/hpcc-js-wasm#116]
When I use the current version (1.15.6) in a Next.JS App then I get this error in the browser:

![image](https://user-images.githubusercontent.com/6124140/189173823-07345878-b4e0-4b4e-b17d-37a8444b488f.png)

(This is an extension of https://github.com/hpcc-systems/hpcc-js-wasm/issues/115 which has been closed by github and I can't reopen that issue.)

**Comment by GordonSmith** [comment]
Can you try 1.15.7

**Comment by mrdrogdrog** [comment]
Right in that moment when you sent that comment, I noticed that you released 1.15.7 :laughing: 

No I haven't tried that version yet because the other post said 1.15.6. Gonna try it right now :)

**Comment by mrdrogdrog** [comment]
Works perfectly. Thank you very much :heart: 

![image](https://user-images.githubusercontent.com/6124140/189175854-54375aab-7e5c-4558-9069-f11f757c04f3.png)
