### ISSUE TITLE
Demo with graphvizSync not working

### ISSUE THREAD

**Issue by pamelafox** [hpcc-systems/hpcc-js-wasm#146]
The following demo has JS errors:
https://raw.githack.com/hpcc-systems/hpcc-js-wasm/trunk/hw-graphviz.html

I'm not sure if the demo is linked, so it may not matter, but I bring it up since my own website had the same issues, and perhaps I originally got the code from that demo or a similar one.

Here's the commit I made to fix my site:
https://github.com/pamelafox/recursive-visualizations/commit/446a8b67619f2d8925744856a4d6d7efcbd09eed

A similar change could be made to that demo, or it could be deleted. I'm not sure what changed, I think it must have been a fairly recent change.

Thanks!

**Comment by GordonSmith** [comment]
Thanks for pointing it out - looks like they need to be upgraded to work with V2 (as per your fix). 

And yes they were primarily for my dev testing!

**Comment by GordonSmith** [comment]
BTW I liked https://www.recursionvisualizer.com/ !

**Comment by pamelafox** [comment]
Thank you! And thanks for the great package :)
