### ISSUE TITLE
Import error in TypeScript

### ISSUE THREAD

**Issue by ablaszkiewicz** [hpcc-systems/hpcc-js-wasm#154]
When trying to import zstd this way:
```
import { Zstd } from '@hpcc-js/wasm/zstd';
```

I am getting:
```
src/shared/S3Bucket.ts:1:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@hpcc-js/wasm/zstd")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/aleksander/Documents/GitRepos/ais-s3-compactor/package.json'.
```

Things I tried:
- change `type` to `module` in my `package.json` as the error suggets but then I get bazillion errors related to all my imports,
- use `const Zstd = import('@hpcc-js/wasm/zstd');` as the error suggets but then I get `Zstd.load is not a function`,
- try different package versions: `2.5.0` and `2.1.1`.

Things I know:
- I read TypeScript notes in the readme and I updated `"moduleResolution": "Node16"`.

Specs:
- Mac M1,
- Node v19.6.0,
- @hpcc-js/wasm 2.8.0,
- ts 4.8.4.

**Comment by GordonSmith** [comment]
This error means you are importing a ESM module from a CommonJS module, try the following:
```
import { Zstd } from '@hpcc-js/wasm/zstd.umd';
```

**Comment by ablaszkiewicz** [comment]
@GordonSmith this one throws
```
Cannot find module '@hpcc-js/wasm/zstd.umd' or its corresponding type declarations.
```

**Comment by GordonSmith** [comment]
(Am not at a PC I can test with), try one of the following:
```
import { Zstd } from '@hpcc-js/wasm/dist/zstd.umd'

import { Zstd } from '@hpcc-js/wasm/dist/zstd.umd.js'

import { Zstd } from '@hpcc-js/wasm/dist/index.umd'

import { Zstd } from '@hpcc-js/wasm/dist/index.umd.js'

import { Zstd } from '@hpcc-js/wasm/dist/index.umd'
```

**Comment by ablaszkiewicz** [comment]
Your first 4 imports throw:
```
Cannot find module '@hpcc-js/wasm/zstd.umd' or its corresponding type declarations.
```

5th import throws the same error as in the post.

**Comment by ablaszkiewicz** [comment]
Only imports I am allowed to make are from VSCode's "smart menu":

<img width="380" alt="image" src="https://user-images.githubusercontent.com/54682207/218818844-0dafbcb3-5431-4a72-aac6-d43fed29d599.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/54682207/218818921-65e31134-38d4-4749-be23-96247271e1bf.png">

Every other imports says `Cannot find module`

**Comment by GordonSmith** [comment]
The following should work and preserve typings:

```ts
async function importZstd() {
    const zstdModule = await import("@hpcc-js/wasm/zstd");
    return await zstdModule.Zstd.load();
}

importZstd().then(zstd => {
    console.log(zstd.version());
});

```

**Comment by ablaszkiewicz** [comment]
It works. Thank you!
