### ISSUE TITLE
Arrow shapes seem to ignore repetition of shape names 

### ISSUE THREAD

**Issue by borango** [hpcc-systems/hpcc-js-wasm#165]
To reproduce, see this as the expected rendering:

https://observablehq.com/d/aeeb7e36de20f2b0

... and the hpcc implementation which renders only 1 arrow in stead of 2:

https://observablehq.com/d/ca61a29c9913c0b2

This error pattern seems to be independent of a particular arrow name (vee, normal...) and whether it is in head or tail position. The repetition gets ignored in all cases that I had tested.

**Comment by GordonSmith** [comment]
Looks like a Graphviz regression introduced around v8.x.x - I have opened an issue here:  https://gitlab.com/graphviz/graphviz/-/issues/2406 

If you lock @hpcc-js/wasm to version 2.8.0 you will get Graphviz version v7.1.0 which appears to render correctly.

**Comment by GordonSmith** [comment]
@borango the upstream fix is now live (GraphViz version 9.0.0)
