### ISSUE TITLE
Graphviz Library does not scale to meet layout w/ 1000 nodes +

### ISSUE THREAD

**Issue by akbog** [hpcc-systems/hpcc-js-wasm#166]
I wanted to use the wasm implementation of graphviz instead of the deprecated [dagre.js](https://github.com/dagrejs/dagre) in order to generate a dot layout for 1000+ node graph (the idea being that graphviz is far more universal than dagre, and could be pre-computed in a variety of backends). After a few seconds of processing the layout I get the following:

```typescript
graphviz.ts:153 Uncaught (in promise) Error: Maximum call stack size exceeded
    at Q.layout (graphviz.ts:153:19)
```

It's clear from the below layout function that this is due to graphviz calling it's layout function recursively:

```c++
layout(dotSource: string, outputFormat: Format = "svg", layoutEngine: Engine = "dot", options?: Options): string {
        if (!dotSource) return "";
        const graphViz = new this._module.Graphviz(options?.yInvert ? 1 : 0, options?.nop ? options?.nop : 0);
        let retVal = "";
        let errorMsg = "";
        try {
            createFiles(graphViz, options);
            try {
                retVal = graphViz.layout(dotSource, outputFormat, layoutEngine);
            } catch (e: any) {
                errorMsg = e.message;
            };
            errorMsg = graphViz.lastError() || errorMsg;
        } finally {
            this._module.destroy(graphViz);
        }
        if (!retVal && errorMsg) {
            Graphviz.unload();
            throw new Error(errorMsg);
        }
        return retVal;
    }
```

There is not really a reason to use wasm if it is not more performant in the browser than it's sibling js implementations! Just something to keep in mind while building this project.

**Comment by hlvlad** [comment]
Is this function really called recursively? Isn't `this._module.Graphviz` just wasm module and not this class instance?

**Comment by akbog** [comment]
It's calling `graphViz.layout(dotSource, outputFormat, layoutEngine);` recursively

**Comment by GordonSmith** [comment]
@akblob - can you provide a sample DOT file that reproduces the problem?

**Comment by GordonSmith** [comment]
Closing as no dot sample provided to reproduce...
