### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by taylorh140** [hpcc-systems/hpcc-js-wasm#172]
I would like to build a wasm plugin for a different project and I'm curious how you were able to get graphviz 8.1.0 compiled to wasm. I would like to do something similar but I don't see any details for building that part. I was looking at some of the cmake files and the docker file but I don't think I see how it was done quite yet and I would really like to be able to duplicate your work.

If you could add some details on how to build the expat/graphviz dependencies components that would be really helpful.

**Comment by GordonSmith** [comment]
For libs you mention I am using "vcpkg" to download and compile see:
1. `https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/vcpkg.json`
2. https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/scripts/cpp-install-vcpkg.sh

These create "static" libs for those libraries with emscripten.

Next those libe are linked in with the wrapper cpp file here:  https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/src-cpp/graphviz/CMakeLists.txt
