### ISSUE TITLE
vite failed to load graphvizlib.wasm

### ISSUE THREAD

**Issue by linlinyang** [hpcc-systems/hpcc-js-wasm#175]
// package.json
dependencies: {
"d3-graphviz": "^4.1.1",
}

// my code in vite
graphviz('#flowDiagram', {
    useWorker: false,
  })
    .options({
      height: container.offsetHeight,
      width: container.offsetWidth,
    })
    .fit(true)
    .renderDot(content);

// throw error: failed to load graphvizlib.wasm
// i have add base vue-route path

**Comment by GordonSmith** [comment]
This will have been resolved with v2 of @hpcc-js/wasm, which is included in d3-graphviz v5 I believe?

Can you confirm if this is the case?

**Comment by linlinyang** [comment]
> This will have been resolved with v2 of @hpcc-js/wasm, which is included in d3-graphviz v5 I believe?
> 
> Can you confirm if this is the case?

yes

**Comment by GordonSmith** [comment]
I don't believe this is an issue now.
