### ISSUE TITLE
Sometimes I get a node without label (demo on viz-js.com)

### ISSUE THREAD

**Issue by DavidMoerman** [hpcc-systems/hpcc-js-wasm#199]
In the current version of hpcc/graphviz, I regularly get nodes without label in the generated SVG. I can easily reproduce the problem in viz-js.com; Please see the reproduction in this video clip: https://youtu.be/M-mhesrSm7w
In the video the initial generation run is ok, but as soon as I start changing a label, the issue appears. Sometimes the problem is already there in the first run.
In the picture below, the bottom node should have a label.

I have attached the DOT file.

[sample.dot.txt](https://github.com/hpcc-systems/hpcc-js-wasm/files/13395048/sample.dot.txt)
![image](https://github.com/hpcc-systems/hpcc-js-wasm/assets/145779154/58f97261-a662-45fc-a024-c855186f4b87)

**Comment by GordonSmith** [comment]
FYI - I just did a quick test here:  https://observablehq.com/@gordonsmith/graphviz  and see something similar to you description...

I would suggest opening a ticket here:  https://gitlab.com/graphviz/graphviz/-/issues as it looks like a memory corruption issue...

**Comment by GordonSmith** [comment]
I don't believe this is an issue in the WebAssembly layer...
