### ISSUE TITLE
Adding `gvpack`

### ISSUE THREAD

**Issue by azriel91** [hpcc-systems/hpcc-js-wasm#202]
Heya, is it much work to add [`gvpack`](https://graphviz.org/docs/cli/gvpack/) as a WASM library?

It's a standalone binary:

* [`gvpack.cpp`](https://gitlab.com/graphviz/graphviz/-/blob/main/cmd/tools/gvpack.cpp)
* [CMakeLists.txt](https://gitlab.com/graphviz/graphviz/-/blob/main/cmd/tools/CMakeLists.txt#L285-288)

Which I suppose means the parts of the code that aren't main / arg parsing would have to be split into a library before it can be compiled to WASM.

**Comment by GordonSmith** [comment]
Basically it would be mostly scafolding type work:
1. Extend [src-cpp/graphviz/main.idl](https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/) with the new method
2. Implement the method in [src-cpp/graphviz/main.cpp](https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/src-cpp/graphviz/main.cpp) - which is mostly cut and paste from your link above
3. Wrap the call in TypeScript here:  [src-ts/graphviz.ts](https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/src-ts/graphviz.ts) which will be mostly documentation!
4. Add a new "bin" [gvpack-wasm.ts](https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/src-ts/__bin__) which will be very similar to the existing `dot-wasm` call.

**Comment by azriel91** [comment]
I might contribute in a few months -- I'm still figuring out what this `dot_ix` project ([repo](https://github.com/azriel91/dot_ix), [demo](https://azriel.im/dot_ix/?src=hierarchy%3A%0A%20%20a%3A%20%7B%7D%0A%20%20b%3A%20%7B%7D%0A%20%20c%3A%20%7B%7D%0A%20%20d%3A%20%7B%7D%0Aedges%3A%0A%20%20ab%3A%20%5Ba%2C%20b%5D%0A%20%20bc%3A%20%5Bb%2C%20c%5D%0A%20%20cd%3A%20%5Bc%2C%20d%5D%0Anode_infos%3A%0A%20%20a%3A%20%7B%20name%3A%20A%20%7D%0A%20%20b%3A%20%7B%20name%3A%20B%20%7D%0A%20%20c%3A%20%7B%20name%3A%20C%20%7D%0A%20%20d%3A%20%7B%20name%3A%20D%20%7D%0Atailwind_classes%3A%0A%20%20a%3A%20%3E-%0A%20%20%20%20%5B%26%3Epath%5D%3Afill-green-300%0A%20%20%20%20%5B%26%3Epath%5D%3Astroke-1%0A%20%20%20%20%5B%26%3Epath%5D%3Astroke-green-600%0A%20%20%20%20%5B%26%3Epath%5D%3Ahover%3Afill-green-200%0A%20%20%20%20%5B%26%3Epath%5D%3Ahover%3Astroke-green-600%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-1%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-lime-600%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-dashed%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Arounded-xl%0A%20%20%20%20cursor-pointer%0A%20%20b%3A%20%3E-%0A%20%20%20%20%5B%26%3Epath%5D%3Afill-blue-300%0A%20%20%20%20%5B%26%3Epath%5D%3Astroke-2%0A%20%20%20%20%5B%26%3Epath%5D%3A%5Bstroke-dasharray%3A4%5D%0A%20%20%20%20%5B%26%3Epath%5D%3A%5Bstroke-dashoffset%3A1%5D%0A%20%20%20%20%5B%26%3Epath%5D%3Aanimate-spin%0A%20%20%20%20%5B%26%3Epath%5D%3Aorigin-%5B32%25_-26%25%5D%0A%20%20%20%20%5B%26%3Epath%5D%3Astroke-blue-600%0A%20%20%20%20%5B%26%3Epath%5D%3Ahover%3Afill-blue-200%0A%20%20%20%20%5B%26%3Epath%5D%3Ahover%3Astroke-blue-600%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-1%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-lime-600%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-dashed%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Arounded-xl%0A%20%20%20%20cursor-pointer%0A%20%20ab%3A%20%3E-%0A%20%20%20%20%5B%26%3Epath%5D%3Astroke-1%0A%20%20%20%20%5B%26%3Epath%5D%3Astroke-green-600%0A%20%20%20%20%5B%26%3Epolygon%5D%3Afill-green-600%0A%20%20%20%20%5B%26%3Epolygon%5D%3Astroke-1%0A%20%20%20%20%5B%26%3Epolygon%5D%3Astroke-green-600%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-1%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-lime-600%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Aoutline-dashed%0A%20%20%20%20%5B%26%3Epath%5D%3Afocus%3Arounded-xl%0A%20%20%20%20cursor-pointer%0A)) is going to look like.

`gvpack` will be useful if it makes sense to generate a number of smaller graphs and then pack them together, instead of one big dot graph and playing with ranks and invisible edges to adjust the layout.

Shall close this for now, I can open another issue / PR if I end up going down that path.

Thank you very much 🙇!

**Comment by GordonSmith** [comment]
If you do need this feature in the future, I would be asking for some sample DOT files and a mocked up JS to how you might expect it to work.
