### ISSUE TITLE
Transitive reduction filter for directed graphs - Graphviz 

### ISSUE THREAD

**Issue by albertorizzi** [hpcc-systems/hpcc-js-wasm#210]
Hello, I'm using d3-graphviz to draw a directed graph.

I need to apply [tred](https://graphviz.org/pdf/tred.1.pdf). Is it possible with this library? If not, how can I apply this algorithm?

**Comment by GordonSmith** [comment]
If its part of the GraphViz source code, then it should be possible - I was unable to find a reference to it on GitLab though...

**Comment by magjac** [comment]
It's underway: https://gitlab.com/graphviz/graphviz/-/merge_requests/3511.

**Comment by Smattr** [comment]
In the case of `tred` specifically, the changes for this were actually already merged in https://gitlab.com/graphviz/graphviz/-/merge_requests/3492. This should make it into Graphviz 10.0.0.

**Comment by GordonSmith** [comment]
Are there any tests for:
* unflatten
* acyclic
* tred 

I am not seeing anything specific in gitlab?

**Comment by Smattr** [comment]
Unfortunately not that I am aware of.

**Comment by albertorizzi** [comment]
Thank you very much, so can I use the library with `npm i --save @hpcc-js/wasm`?

**Comment by GordonSmith** [comment]
@albertorizzi not yet - While I have made the required changes to this library, I have based it against the current Graphviz "main" branch - I wasn't planning on releasing until https://gitlab.com/graphviz/graphviz v10.x is officially released...

**Comment by GordonSmith** [comment]
@albertorizzi, @Smattr, @magjac - I just added support for doing pre-releases and released:  [v2.16.0-next.2](https://github.com/hpcc-systems/hpcc-js-wasm/releases/tag/v2.16.0-next.2) here and on npmjs...

**Comment by Smattr** [comment]
Thanks. As you may have noticed, [we’re struggling](https://gitlab.com/graphviz/graphviz/-/issues/2500#note_1756399853). The Graphviz workflows remain a Rube Goldberg machine.

**Comment by Smattr** [comment]
FYI we appear to have finally bypassed the problems and cut the release as 10.0.1.

**Comment by GordonSmith** [comment]
@Smattr - I found a small issue with the zlib AUTO support, added comments to the orig PR:  https://gitlab.com/graphviz/graphviz/-/merge_requests/3464#note_1767694502 
It might be applicable to some of the other tri-state option changes?
