### ISSUE TITLE
Graphviz: Getting Inline images to work without duplication

### ISSUE THREAD

**Issue by azriel91** [hpcc-systems/hpcc-js-wasm#232]
Heya, from https://github.com/hpcc-systems/hpcc-js-wasm/issues/145 and some experimentation:

* I could get data URLs to show base64 encoded inline images in a generated dot graph, when both the `image` attribute and the `images` array contain the base64 data.
* I couldn't get an image to render when I tried to define the content in (both `images` and) `files` -- the `<image>` tag exists, but is empty:

    ![image](https://github.com/user-attachments/assets/9e97b440-dd73-479b-b539-2adb458a8ccf)

The issue I'd like to solve is not requiring the inline image data to be defined twice -- I may be embedding a lot of images, and doubling the data isn't efficient.

From experimentation / investigation:

1. The `images` array must have an entry for the `image` path for the `<image />` tag to be rendered.
2. I attempted using / not using `imagepath` to write bytes to the file content, but in [graphviz/main.cpp](https://github.com/hpcc-systems/hpcc-js-wasm/blob/v2.18.2/src-cpp/graphviz/main.cpp#L80), the data must be valid UTF8, so I wonder if that's preventing the content from being written.
3. What is `FS` in that `main.cpp`? I couldn't find where it's defined.
4. Maybe [`xlink:href`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) is the issue -- I'm not sure where it instructs the browser to load the image file from.

index.html:

```html
<!DOCTYPE html>
<!-- Content-Type: application/xhtml+xml -->
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" >
<body>
    <div id="1">1</div>
    <script type="module">

const dot_sample_img=`digraph G { node[shape=box]
blue_file[label="blue_file" image="blue.png" imagepath="/"]

blue_inline[label="blue_inline" image="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZBAMAAAA2x5hQAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAADUExURUeK/z7BOdMAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAOSURBVCjPYxgFNAMMDAABXgABAvs87wAAAABJRU5ErkJggg=="]
}`;

const images=[
    {
        path: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZBAMAAAA2x5hQAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAADUExURUeK/z7BOdMAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAOSURBVCjPYxgFNAMMDAABXgABAvs87wAAAABJRU5ErkJggg==",
        width: "25px",
        height: "25px"
    }
    ,
    {
        path: "blue.png",
        width: "25px",
        height: "25px"
    }
];

const files = [
    {
        path: "/blue.png",
        data:
            "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A\x00\x00\x00\x0D\x49\x48\x44\x52\x00\x00\x00\x19\x00\x00\x00\x19\x04\x03\x00\x00\x00\x36\xC7\x98\x50\x00\x00\x00\x01\x73\x52\x47\x42\x00\xAE\xCE\x1C\xE9\x00\x00\x00\x04\x67\x41\x4D\x41\x00\x00\xB1\x8F\x0B\xFC\x61\x05\x00\x00\x00\x03\x50\x4C\x54\x45\x47\x8A\xFF\x3E\xC1\x39\xD3\x00\x00\x00\x09\x70\x48\x59\x73\x00\x00\x0E\xC2\x00\x00\x0E\xC2\x01\x15\x28\x4A\x80\x00\x00\x00\x0E\x49\x44\x41\x54\x28\xCF\x63\x18\x05\x34\x03\x0C\x0C\x00\x01\x5E\x00\x01\x02\xFB\x3C\xEF\x00\x00\x00\x00\x49\x45\x4E\x44\xAE\x42\x60\x82"
    }
];

import { Graphviz } from "https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/index.js";
const graphviz = await Graphviz.load();
layout(dot_sample_img, "1");

function layout( dot, domId ) {
    document.getElementById(domId).innerHTML = graphviz.dot(
        dot,
        "svg",
        {
            images: images,
            files: files
        }
    );
}

</script>
</body>
</html>
```

**Comment by azriel91** [comment]
ℹ️ ah, [`xlink:href`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) is part of the issue -- the browser loads the image as a regular resource, i.e. if I put `blue.png` in the same folder as `index.html`, it renders.

So I guess the question is, where does `FS` write to in main.cpp, and is it a non-breaking solution to:

1. Have the image data be written inline into the SVG (`<defs><image ../></defs>` maybe?)
2. Change the generated `xlink:href` value to reference that image data

**Comment by GordonSmith** [comment]
FYI `FS` is a virtual file system which resides in memory, when dot processes images, it resolves the "path" to a file in this virtual filesystem and loads the image content from there.

Your issue is that the "path to the file" and the "content of the file" are the same data, IOW your "file path" is huge!

To solve this you can create an URL which references the image as a blob and pass that into GraphViz (I am sure this code could be improved depending on the source of your image):

```html
<!DOCTYPE html>
<!-- Content-Type: application/xhtml+xml -->
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">

<body>
    <div id="1">1</div>
    <script type="module">

        const base64Image = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZBAMAAAA2x5hQAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAADUExURUeK/z7BOdMAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAOSURBVCjPYxgFNAMMDAABXgABAvs87wAAAABJRU5ErkJggg==";
        const byteCharacters = atob(base64Image.split(',')[1]);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        const blob = new Blob([byteArray], { type: 'image/png' });
        const fakeUrl = URL.createObjectURL(blob);

        const dot_sample_img = `digraph G { node[shape=box]
blue_file[label="blue_file" image="blue.png" imagepath="/"]

blue_inline[label="${fakeUrl}" image="${fakeUrl}"]
}`;

        const images = [
            {
                path: fakeUrl,
                width: "25px",
                height: "25px"
            }
            ,
            {
                path: "blue.png",
                width: "25px",
                height: "25px"
            }
        ];

        const files = [
            {
                path: "/blue.png",
                data:
                    "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A\x00\x00\x00\x0D\x49\x48\x44\x52\x00\x00\x00\x19\x00\x00\x00\x19\x04\x03\x00\x00\x00\x36\xC7\x98\x50\x00\x00\x00\x01\x73\x52\x47\x42\x00\xAE\xCE\x1C\xE9\x00\x00\x00\x04\x67\x41\x4D\x41\x00\x00\xB1\x8F\x0B\xFC\x61\x05\x00\x00\x00\x03\x50\x4C\x54\x45\x47\x8A\xFF\x3E\xC1\x39\xD3\x00\x00\x00\x09\x70\x48\x59\x73\x00\x00\x0E\xC2\x00\x00\x0E\xC2\x01\x15\x28\x4A\x80\x00\x00\x00\x0E\x49\x44\x41\x54\x28\xCF\x63\x18\x05\x34\x03\x0C\x0C\x00\x01\x5E\x00\x01\x02\xFB\x3C\xEF\x00\x00\x00\x00\x49\x45\x4E\x44\xAE\x42\x60\x82"
            }
        ];

        import { Graphviz } from "https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/index.js";
        const graphviz = await Graphviz.load();
        layout(dot_sample_img, "1");

        function layout(dot, domId) {
            document.getElementById(domId).innerHTML = graphviz.dot(
                dot,
                "svg",
                {
                    images: images,
                    files: files
                }
            );
        }

    </script>
</body>

</html>
```

**Comment by azriel91** [comment]
@GordonSmith Wow, thank you very much 🙇‍♂️! Creating an object URL never crossed my mind, and that certainly solves the issue better than a solution I was trying.

If you're interested what this is for, check out: https://azriel.im/dot_ix/ and click on Step 1 ~ Step 4.
Right now it's animating `<path>`s, but rendering images could help clarify what nodes represent.

Thank you for being consistently generous with your time and skill and energy.

**Comment by GordonSmith** [comment]
@azriel91 very pretty!

**Comment by azriel91** [comment]
It's something I'm working on, and it certainly is quite far from stable:

1. It's still in the experimentation phase for how much clarity / understanding can we deliver through a diagram without crossing the line of clutter.

	Too much information reduces clarity, yet we want to show the information when the user is ready for it.

2. I picked the "struct of arrays" approach instead of "array of structs":
	- adding more `node_<attr>` maps is friendlier for backward compatibility (don't need to add a new field)
	- usually when dealing with a particular attribute, you aren't looking at the other attributes, so it saves scrolling / searching for that one attribute within a node's 10 attributes.

3. The above human-input UI is one way of generating diagrams, but I also have programmatic input in mind, where as an automated process runs, the user can *see* things being downloaded / servers being modified.

	Bonus points for styling a node / edge red when an error happens, so the diagram shows where the error occurred, without needing a person to interpret it from a stack trace.
