### ISSUE TITLE
Version 2.20.0 (currently the latest on npm) is not listed in the changelog

### ISSUE THREAD

**Issue by magjac** [hpcc-systems/hpcc-js-wasm#255]
- https://www.npmjs.com/package/@hpcc-js/wasm
- https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/CHANGELOG.md

**Comment by GordonSmith** [comment]
FYI - I converted the repo to a mono-repo with individual packages, so you can now switch to "@hpcc-js/wasm-graphviz" for a more minimal dependency.  
@hpcc-js/wasm is relocated to:  https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/packages/wasm and is backward compatible.

**Comment by magjac** [comment]
Yes I saw that, but decided to get out a release based on "@hpcc-js/wasm" v2.20.0 before changing that.

**Comment by magjac** [comment]
There's still no changelog entry for the latest version found through npm (2.21.0).

Steps to reproduce:

1. Visit https://www.npmjs.com/package/@hpcc-js/wasm
2. Click on the **Repository** link: https://github.com/hpcc-systems/hpcc-js-wasm 
3. Click on **CHANGLELOG.md**: https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/CHANGELOG.md

There are no changelog entries between 2.18.1 and 3.0.0. Also, the latest version in the changelog (3.2.0) is not listed as the latest on npm.

I'm aware that the missing versions are found in https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/packages/wasm/CHANGELOG.md, but that is not what you find through npm.
