### ISSUE TITLE
Can't resolve duckdb

### ISSUE THREAD

**Issue by Montmorency** [hpcc-systems/hpcc-js-wasm#257]
I had a workflow with esbuild bundling  hpcc/wasm and the d3-graphviz and some other code. 

Since updating the packages I'm getting an error when running the bundler: 
```
✘ [ERROR] Could not resolve "./duckdb.js"

    node_modules/@hpcc-js/wasm/dist/index.js:3:893872:
      3 │ ...s=>s.Base91.load())}i.load=o})(Sa||={});var Qa;(i=>{function o(){return import("./duckdb.js").then(s=>s.DuckDB.load())}i.load=o})(Qa||={});var Ja;(i=>{function o(){return ...
        ╵                                                                                   ~~~~~~~~~~~~~ 
        ```
        It looks like it's trying to find a local duckdb.js in the dist folder but can't resolve it? The other imports base91.js and expat.js all seem to be present.

Cheers

**Comment by kogratte** [comment]
Same thing here :)

**Comment by GordonSmith** [comment]
Was this in NodeJS or Browser?

**Comment by Montmorency** [comment]
> Was this in NodeJS or Browser?

Browser.
