### ISSUE TITLE
Inverting y axis

### ISSUE THREAD

**Issue by meoyawn** [hpcc-systems/hpcc-js-wasm#32]
Would be cool to have the `yInvert` option (see https://github.com/mdaines/viz.js/wiki/API#render-options) when outputting JSON and doing a custom SVG render

**Comment by GordonSmith** [comment]
@meoyawn - I have added support as per Viz.js in this PR:  https://github.com/hpcc-systems/hpcc-js-wasm/pull/33, but am not 100% what to look for!
But I did test that it does something!

Can you review the code and I will pull and release?

**Comment by GordonSmith** [comment]
REsolved with:  https://github.com/hpcc-systems/hpcc-js-wasm/pull/33

**Comment by meoyawn** [comment]
@GordonSmith pulled 0.3.15 and it works! Thank you so much! That was fast
