### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by joa** [hpcc-systems/hpcc-js-wasm#47]
Importing the minified distribution fails. 

```
index.min.js:1 Uncaught (in promise) RuntimeError: abort(LinkError: WebAssembly.instantiate(): Import #45 module="a" function="T" error: function import requires a callable). Build with -s ASSERTIONS=1 for more info.
    at L (https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/index.min.js:1:54376)
    at https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/index.min.js:1:104280
```

Steps to reproduce:
1. Copy HTML from https://github.com/hpcc-systems/hpcc-js-wasm#hello-world
2. Save to file
3. Open file in a browser

**Comment by joa** [comment]
`Empty cache & hard reload` fixes this. I see some commits to purge the jsdelivr cache. Maybe the commands were not executed?

**Comment by GordonSmith** [comment]
@joa - You typically see that error when the JS loader code and the wasm files are out of sync (from different versions).

While I do flush the jsdelivr server your issue sounds like it was simply a local caching issue?

**Comment by joa** [comment]
I don't think any additional local caching was involved other than the browser's cache. I do assume Chrome to honor proper caching headers.

It's hard to tell now. I will let you know if this happens again and make a trace of the actual requests and jsdelivr response should this reappear.

**Comment by GordonSmith** [comment]
FWIW after I release, I tend to go to:  https://observablehq.com/@gordonsmith/graphviz to check the jsdelivr stuff and it was working fine when I manually flushed the cache.
Not sure how your example got out of sync, but please let me know if you can reproduce it in the future.

**Comment by ikebastuz** [comment]
Syncing package version and WASM file helped me.

I served WASM file from some version of library. Once it updated (with regular npm install, no hard-version was used) - started having this error.

Updated package to `1.15.0`, served WASM from it - everything started working again.
