### ISSUE TITLE
Runtime error on firefox when opening local html files relying on hpcc-js/wasm

### ISSUE THREAD

**Issue by betonniere** [hpcc-systems/hpcc-js-wasm#62]
The "official" [hello world](https://github.com/hpcc-systems/hpcc-js-wasm#hello-world) example doesn't work itself when it's loaded from the local file system.

The web developer console logs:
```diff
- Uncaught (in promise) RuntimeError: abort(LinkError: import object field 'Q' is not a Function). Build with -s ASSERTIONS=1 for more info.
    L https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/index.min.js:1
    i https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/index.min.js:1
```

**Comment by GordonSmith** [comment]
Weird its working fine for me in Chrome and Firefox:

![image](https://user-images.githubusercontent.com/966863/115499634-a7792e00-a267-11eb-961c-6411e381a941.png)

![image](https://user-images.githubusercontent.com/966863/115499592-94fef480-a267-11eb-9840-fa56c90ef409.png)

**Comment by GordonSmith** [comment]
I added the helloworld.html example to the repo and the following URL is working fine here:

https://raw.githack.com/hpcc-systems/hpcc-js-wasm/trunk/helloworld.html

**Comment by betonniere** [comment]
I finally managed to make it works. For that I had to reinitialized Firefox and everything works like a charm now.  
I ignore the root cause of the issue, but it came without doubt from my environment.

I'm sincerely sorry for the inconvenience.

**Comment by GordonSmith** [comment]
@betonniere no problem - I wonder if FF had a disable wasm setting?
