### ISSUE TITLE
RangeError when handling large graphs

### ISSUE THREAD

**Issue by MiguelKrimp** [hpcc-systems/hpcc-js-wasm#89]
Hi, I'd like to use this for a project at work and so far it works like a charm, except for one thing.
When handling rather large graphs (>10K nodes) I run into the following error:
```
RangeError: Maximum call stack size exceeded
    at graphvizlib.wasm:0x40f63
    at graphvizlib.wasm:0x415da
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
    at graphvizlib.wasm:0x415f4
```

The layout still finishes but only returns part of the graph, rendering the result useless.
I'm currently using Chrome Version 97.0.4692.99 and the graph is a directed acyclic graph.

Is there a way to fix this? I'd look into it myself, but I don't know much about WASM.

**Comment by GordonSmith** [comment]
Depend...  I would suggest posting to https://forum.graphviz.org/ as the graphviz developers are very helpful (and there is a new release on the way which is fixing an issue similar to this, I think...).

**Comment by GordonSmith** [comment]
Closing - if the graph crashes in the CLI then it is going to crash in the wasm...
