### ISSUE TITLE
Is it possible to pass options to the layout engine ?

### ISSUE THREAD

**Issue by kasra0** [hpcc-systems/hpcc-js-wasm#97]
Hi,

I need to pass the -n2 option to neato.
I tried something like 

`$ dot-wasm -K neato -n2 pack.dot  > out.svg`
But I don't have the right result.

With graphviz I have this command :

`$ neato -n2 pack.dot -Tsvg > out.svg`

that gives :
![out](https://user-images.githubusercontent.com/16036382/161440109-7b918d0e-7c9a-4d7b-a9b1-46d561d70db1.png)

If I don't pass the n2 option I have the wrong result ( same as dot-wasm -K neato -n2 pack.dot  > out.svg)
`$ neato  pack.dot -Tsvg > out.svg`
![without-n2](https://user-images.githubusercontent.com/16036382/161440213-da36de0f-17eb-4f56-8232-e8605dea8d07.png)

the input file: 
[pack.txt](https://github.com/hpcc-systems/hpcc-js-wasm/files/8405136/pack.txt)

thanks

**Comment by GordonSmith** [comment]
@kasra0 looks like its currently not supported in the command line interface (but is supported in the JavaScript API), I will add it.

**Comment by GordonSmith** [comment]
Resolved with:  https://github.com/hpcc-systems/hpcc-js-wasm/pull/98

**Comment by BBX999** [comment]
> @kasra0 looks like its currently not supported in the command line interface (but is supported in the JavaScript API), I will add it.

@GordonSmith Could you please clarity how it is possible to pass the -n2 option to the neato layout engine via the JavaScript API? I couldn't find anything about that in the documentation. Thanks!

**Comment by BBX999** [comment]
Answering my own question for those who this may come up for, the 'nop' options seems to control the -n flag, so -n2 would be { nop: 2 }. This was a useful forum discussion of the 'n' option as well:

https://forum.graphviz.org/t/what-is-the-purpose-of-the-n2-option-with-neato/1107
